Cls
Input "WHAT IS YOUR NAME"; NAME$
Input "HOW OLD ARE YOU"; AGE
If AGE < 18 Then
    Print "DEAR,"; Tab(2), NAME$, "YOU ARE NOT ELIGIBLE FOR HAVING A GMAIL ACCOUNT"
Else
    Print "DEAR"; Tab(2), NAME$, "YOU ARE ELIGIBLE FOR HAVING A GMAIL ACCOUNT"
End If
End

