Rem PROGRAM TO CALCULATE RESULT
Cls
Input "ENTER THE MARKS OF ENGLISH:"; E
Input "ENTER THE MARKS OF HINDI:"; H
Input "ENTER THE MARKS OF SANSKRIT:"; SKT
Input "ENTER THE MARKS OF MATHEMATICS:"; M
Input "ENTER THE MARKS OF SCIENCE:"; SCI
Input "ENTER THE MARKS OF SOCIAL SCIENCE:"; S.SCI
Input "ENTER THE MARKS OF DHARAM SIKSHA:"; D.S
Input "ENTER THE MAX MARKS:"; MAX
TOTAL = E + H + SKT + M + SCI + S.SCI + D.S
PER = TOTAL / MAX * 100
Print "TOTAL MARKS:="; TOTAL
Print "PERCENTAGE:="; PER
End

